In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv(r"C:\Juneinter\aaaaaa.csv")

In [3]:
df

Series Name  \
0   1970 [YR1970]   
1   1971 [YR1971]   
2   1972 [YR1972]   
3   1973 [YR1973]   
4   1974 [YR1974]   
5   1975 [YR1975]   
6   1976 [YR1976]   
7   1977 [YR1977]   
8   1978 [YR1978]   
9   1979 [YR1979]   
10  1980 [YR1980]   
11  1981 [YR1981]   
12  1982 [YR1982]   
13  1983 [YR1983]   
14  1984 [YR1984]   
15  1985 [YR1985]   
16  1986 [YR1986]   
17  1987 [YR1987]   
18  1988 [YR1988]   
19  1989 [YR1989]   
20  1990 [YR1990]   
21  1991 [YR1991]   
22  1992 [YR1992]   
23  1993 [YR1993]   
24  1994 [YR1994]   
25  1995 [YR1995]   
26  1996 [YR1996]   
27  1997 [YR1997]   
28  1998 [YR1998]   
29  1999 [YR1999]   
30  2000 [YR2000]   
31  2001 [YR2001]   
32  2002 [YR2002]   
33  2003 [YR2003]   
34  2004 [YR2004]   
35  2005 [YR2005]   
36  2006 [YR2006]   
37  2007 [YR2007]   
38  2008 [YR2008]   
39  2009 [YR2009]   
40  2010 [YR2010]   
41  2011 [YR2011]   
42  2012 [YR2012]   
43  2013 [YR2013]   
44  2014 [YR2014]   
45  2015 [YR2015]   
46  2016 [YR2016]   
47  2017 [YR2017]   
48  2018 [YR2018]   

    General government final consumption expenditure (% of GDP)  \
0                                            9.900530             
1                                           10.194274             
2                                           10.488755             
3                                            8.909041             
4                                            9.648600             
5                                           11.149822             
6                                           10.867122             
7                                           10.798421             
8                                           10.022739             
9                                            9.969304             
10                                          12.067502             
11                                          12.231571             
12                                          11.943136             
13                                          11.277870             
14                                          10.718176             
15                                          10.789252             
16                                          10.441653             
17                                          10.168554             
18                                          10.105405             
19                                          10.968028             
20                                          11.254737             
21                                          11.055680             
22                                          11.396822             
23                                          11.147285             
24                                          10.676206             
25                                          10.400066             
26                                          10.805215             
27                                          10.613615             
28                                          11.834766             
29                                          11.506765             
30                                          11.338342             
31                                          12.186803             
32                                          12.134766             
33                                          12.467763             
34                                          12.789334             
35                                          13.282861             
36                                          13.819209             
37                                          13.928599             
38                                          14.644848             
39                                          15.169299             
40                                          14.471457             
41                                          14.585726             
42                                          14.833439             
43     

In [4]:
x_data=df.iloc[:,1:7].values
y_data=df.iloc[:,[7]].values

In [5]:
print(x_data.shape)
print(y_data.shape,"\n")

print(y_data)

(49, 6)
(49, 1) 

[[2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [0]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [0]
 [2]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [6]:
"""temp_y = y_data #임시 변수
temp_y=tf.squeeze(temp_y).numpy()
temp_y=np.sort(temp_y)

print(temp_y)

standard0_1=round(len(temp_y)/3, 0)   #성장률을 순서대로 세웠을 때 1/3지점
standard1_2=round((len(temp_y)*2)/3, 0)   #성장률을 순서대로 세웠을 때 2/3지점


for i, data in enumerate(temp_y):
    if i+1==standard0_1:
        standard0_1=data
    elif i+1==standard1_2:
        standard1_2=data
        
print(standard0_1)
print(standard1_2)

for i, data in enumerate(y_data):
    if data > standard1_2:
        y_data[i] = 2
    elif data > standard0_1:
        y_data[i] = 1
    else:
        y_data[i] = 0

print(y_data)
Y=np.copy(y_data)   #plt 그릴 때 색깔 구분하기 위해 따로 복사해둠
print(Y)
"""

'temp_y = y_data #임시 변수\ntemp_y=tf.squeeze(temp_y).numpy()\ntemp_y=np.sort(temp_y)\n\nprint(temp_y)\n\nstandard0_1=round(len(temp_y)/3, 0)   #성장률을 순서대로 세웠을 때 1/3지점\nstandard1_2=round((len(temp_y)*2)/3, 0)   #성장률을 순서대로 세웠을 때 2/3지점\n\n\nfor i, data in enumerate(temp_y):\n    if i+1==standard0_1:\n        standard0_1=data\n    elif i+1==standard1_2:\n        standard1_2=data\n        \nprint(standard0_1)\nprint(standard1_2)\n\nfor i, data in enumerate(y_data):\n    if data > standard1_2:\n        y_data[i] = 2\n    elif data > standard0_1:\n        y_data[i] = 1\n    else:\n        y_data[i] = 0\n\nprint(y_data)\nY=np.copy(y_data)   #plt 그릴 때 색깔 구분하기 위해 따로 복사해둠\nprint(Y)\n'

In [7]:
y_data=np.array(y_data, dtype=np.int32) #float를 one_hot하면 오류가 나므로  int로 전환 
print(y_data)

[[2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [0]
 [1]
 [1]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [0]
 [2]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [8]:
#make y_data one_hot_dummy
one_hot_dummy=tf.one_hot(y_data, depth=3)

In [9]:
#int to float
x_data=np.array(x_data, dtype=np.float32)
y_data=np.array(one_hot_dummy, dtype=np.float32)
y_data=np.squeeze(y_data)
print(x_data.shape)
print(y_data.shape)
print(y_data)
print(x_data)

def MinMaxScaler(data):
    numerator=data-np.min(data, 0)
    denominator=np.max(data, 0)-np.min(data, 0) + 1e-7
    return numerator / denominator

x_data=MinMaxScaler(x_data)
print(x_data)

x_train, x_test, y_train, y_test=train_test_split(x_data, y_data, test_size=0.3, random_state=2020)

(49, 6)
(49, 3)
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[  9.90053     25.862316     2.184174    32.58194     15.950341
   11.412     ]
 [ 10.194274    23.376926     1.9713236   35.720734    13.5117035
   15.623     ]
 [ 10.488755    21.475187     1.8759993   38.076904    11.688986
   19.1389    ]
 [  8.909041    24.36202      1.7682927   51.633263     3.221029
   18.437     ]
 [  9.6486      27.256691     1.7127054   55.61111     24.304195
   19

In [10]:
tf.random.set_seed(2000)

W=tf.Variable(tf.random.normal([6, 3], mean=0.0))
b=tf.Variable(tf.random.normal([3], mean=0.0))


def softmax(X):
    z=tf.matmul(X,W)+b
    return tf.nn.softmax(z)

In [11]:
def cost_fn(y_pred, y_actual):
    return tf.reduce_mean(-tf.reduce_sum(y_actual*tf.math.log(y_pred), axis=1))

optimizer=tf.optimizers.SGD(learning_rate=0.001)

In [12]:
for step in range(500001):  #50만번 진행
    with tf.GradientTape() as g:
        pred=softmax(x_train)
        cost=cost_fn(pred, y_train)
        
        gradients=g.gradient(cost, [W,b])
        
    optimizer.apply_gradients(zip(gradients, [W,b]))
    
    if step % 100000 == 0:
        print("cost: \t", cost.numpy())
        print("W: \t", W.numpy())
        print("b: \t", b.numpy())
        print("\n")

cost: 	 2.5291395
W: 	 [[-0.30372903  2.0350745  -0.4264159 ]
 [ 0.30335557  0.6522787   0.13465063]
 [-0.02410628 -0.18719587 -0.25473958]
 [-1.5413924   0.69199795 -1.1592134 ]
 [-0.71623665  1.3543217  -0.7723064 ]
 [-0.47812483 -0.5923489   0.5678252 ]]
b: 	 [-0.4786494   1.4288125   0.78776026]


cost: 	 0.7107463
W: 	 [[ 2.1342623   1.2658699  -2.0950043 ]
 [ 0.21424471  0.3080237   0.5679877 ]
 [-1.6243167  -0.23486185  1.3931355 ]
 [ 0.5401018  -0.4503469  -2.0984395 ]
 [ 0.1270719   0.2941895  -0.55541646]
 [ 1.3055633  -1.9708714   0.1626518 ]]
b: 	 [-0.7883205  1.3043997  1.2212557]


cost: 	 0.6743112
W: 	 [[ 2.633406    1.4727112  -2.800747  ]
 [ 0.26956725  0.0117766   0.8087803 ]
 [-2.286581   -0.04201492  1.8630469 ]
 [ 0.96691674 -0.61987495 -2.3555174 ]
 [ 1.0704756  -0.13040653 -1.0741373 ]
 [ 1.2170103  -2.0696182   0.346354  ]]
b: 	 [-1.1910375  1.6176803  1.3095417]


cost: 	 0.6547117
W: 	 [[ 2.9601145   1.6561472  -3.3108883 ]
 [ 0.3882023  -0.20860721  0.910128

In [13]:
W_hat=W.numpy()
b_hat=b.numpy()

print(W_hat[:,0])
print(x_data[:,0])
print(np.min(x_data[:,0]))
print(np.max(x_data[:,0]))

[ 3.4000664  0.5967882 -3.8834827  1.5526121  2.6158938  0.5700497]
[0.13811146 0.17902915 0.22004955 0.         0.10301831 0.31213427
 0.27275488 0.26318508 0.1551349  0.1476915  0.43996438 0.46281874
 0.4226406  0.32997096 0.2520072  0.2619078  0.21348824 0.17544648
 0.16664995 0.28681085 0.32674855 0.29902056 0.3465406  0.3117809
 0.24616084 0.2076953  0.26413158 0.23744215 0.40754485 0.3618554
 0.33839446 0.45658264 0.449334   0.49571955 0.5405135  0.60926044
 0.68397194 0.6992098  0.7989812  0.8720357  0.77482826 0.7907456
 0.82525134 0.8489449  0.86544037 0.8497692  0.8730493  0.89504004
 1.        ]
0.0
1.0


In [14]:
"""
#xx=np.linspace(tf.min(W_hat[:,0], tf.max(W_hat[:,0])))
#slope=W_hat[0]/W_hat[1]
#yy=-slope*xx-b_hat/w_hat[1]


xx=np.linspace(np.min(x_data[:,0]), np.max(x_data[:,0]))

#line0
slope0=W_hat[0][0]/W_hat[1][0]
y_intercept0=b_hat[0]/W_hat[1][0]
yy0=-slope0*xx-y_intercept0

#line1
slope1=W_hat[0][1]/W_hat[1][1]
y_intercept1=b_hat[1]/W_hat[1][1]
yy1=-slope1*xx-y_intercept1

#line2
slope2=W_hat[0][2]/W_hat[1][2]
y_intercept2=b_hat[2]/W_hat[1][2]
yy2=-slope2*xx-y_intercept2

#빨강은 저성장, 노랑은 전환기, 초록은 성장기
colors=np.where(Y==0, "red", np.where(Y==1, "yellow", "green"))  #3가지 클래스로 구분하기 위해 3가지 색깔 사용
temp0=tf.squeeze(colors)  #차원 축소
color_list=list()  #저장할 빈 리스트 생성
for data in temp0:
    color_list.append(data.numpy().decode("utf-8"))        #이 방법 외에도 2, 1, 0 을 각자 리스트에 넣고 plot 따로 실행해서 하나에 표현해도 됨

plt.scatter(x_data[:,0], x_data[:,1], color=color_list)
plt.plot(xx, yy0, label="line0")
plt.plot(xx, yy1, label="line1")
plt.plot(xx, yy2, label="line2")
plt.legend()
plt.xlim(-0.5,1.5)
plt.ylim(-0.5,1.5)
plt.xlabel("inflation")
plt.ylabel("debt")
plt.show()
"""

'\n#xx=np.linspace(tf.min(W_hat[:,0], tf.max(W_hat[:,0])))\n#slope=W_hat[0]/W_hat[1]\n#yy=-slope*xx-b_hat/w_hat[1]\n\n\nxx=np.linspace(np.min(x_data[:,0]), np.max(x_data[:,0]))\n\n#line0\nslope0=W_hat[0][0]/W_hat[1][0]\ny_intercept0=b_hat[0]/W_hat[1][0]\nyy0=-slope0*xx-y_intercept0\n\n#line1\nslope1=W_hat[0][1]/W_hat[1][1]\ny_intercept1=b_hat[1]/W_hat[1][1]\nyy1=-slope1*xx-y_intercept1\n\n#line2\nslope2=W_hat[0][2]/W_hat[1][2]\ny_intercept2=b_hat[2]/W_hat[1][2]\nyy2=-slope2*xx-y_intercept2\n\n#빨강은 저성장, 노랑은 전환기, 초록은 성장기\ncolors=np.where(Y==0, "red", np.where(Y==1, "yellow", "green"))  #3가지 클래스로 구분하기 위해 3가지 색깔 사용\ntemp0=tf.squeeze(colors)  #차원 축소\ncolor_list=list()  #저장할 빈 리스트 생성\nfor data in temp0:\n    color_list.append(data.numpy().decode("utf-8"))        #이 방법 외에도 2, 1, 0 을 각자 리스트에 넣고 plot 따로 실행해서 하나에 표현해도 됨\n\nplt.scatter(x_data[:,0], x_data[:,1], color=color_list)\nplt.plot(xx, yy0, label="line0")\nplt.plot(xx, yy1, label="line1")\nplt.plot(xx, yy2, label="line2")\nplt.legend()\npl

In [15]:
# train accuracy
predicted=tf.argmax(softmax(x_train), axis=1)
real=tf.argmax(y_train, axis=1)

def accuracy(y_predicted, y_real):
    return tf.reduce_mean(tf.cast(tf.equal(y_predicted, y_real), dtype = tf.float32))

print("train accuracy: ", accuracy(predicted, real).numpy())

train accuracy:  0.7352941


In [16]:
# test accuracy
tested=tf.argmax(softmax(x_test), axis=1)
reall=tf.argmax(y_test, axis=1)
print("test accuracy: ", accuracy(tested, reall).numpy())

test accuracy:  0.6666667


In [21]:
x_test_2019=[[17.03, 31.5579, 0.2, 68.6, 0.4, 38.1]]  #2019년도 인플레이션율, 채무비율

x_test_2019=np.array(x_test_2019, np.float32)  #2는 고도성장 1은 전환기 0은 저성장

print(softmax(x_test_2019).numpy())
x_test_predict_2019=tf.argmax(softmax(x_test_2019), axis=1)
print(x_test_predict_2019.numpy())

[[1. 0. 0.]]
[0]


In [ ]:
W_hat

In [ ]:
b_hat

In [ ]:
slope1=W_hat[0][1]/W_hat[1][1]
y_intercept1=b_hat[1]/W_hat[1][1]